version: "3.8"

services:
  frontend:
    image: technews-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: node server.js